version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - aws cloudformation package --template-file lambda-serverless/template.yml --s3-bucket ${S3_BUCKET} --output-template-file lambda-serverless/output.yml
artifacts:
  type: zip
  files:
    - lambda-serverless/template.yml
    - lambda-serverless/output.yml
